$content = Get-Content 'd:\Hirehack\style.css'
$cleanContent = $content[0..918]
$styles = @(
    '/* Event Countdown Styles */',
    '.countdown-container {',
    '    margin-bottom: 2.5rem;',
    '    padding: 2rem;',
    '    background: rgba(255, 255, 255, 0.4);',
    '    backdrop-filter: blur(8px);',
    '    border-radius: 20px;',
    '    border: 1px solid rgba(255, 255, 255, 0.5);',
    '    box-shadow: 0 10px 30px rgba(103, 58, 183, 0.05);',
    '}',
    '',
    '.countdown-items {',
    '    display: flex;',
    '    justify-content: center;',
    '    gap: 1.5rem;',
    '    margin-bottom: 1.5rem;',
    '}',
    '',
    '.countdown-item {',
    '    display: flex;',
    '    flex-direction: column;',
    '    align-items: center;',
    '    min-width: 80px;',
    '}',
    '',
    '.countdown-item span {',
    '    font-size: 2.5rem;',
    '    font-weight: 800;',
    '    color: #673ab7;',
    '    line-height: 1;',
    '    margin-bottom: 0.5rem;',
    '}',
    '',
    '.countdown-item label {',
    '    font-size: 0.75rem;',
    '    font-weight: 700;',
    '    color: #666;',
    '    letter-spacing: 1px;',
    '    text-transform: uppercase;',
    '}',
    '',
    '.event-msg {',
    '    color: #555;',
    '    font-weight: 600;',
    '    font-size: 1rem;',
    '    margin: 0;',
    '}',
    '',
    '@media (max-width: 600px) {',
    '    .countdown-items { gap: 0.8rem; }',
    '    .countdown-item { min-width: 60px; }',
    '    .countdown-item span { font-size: 1.8rem; }',
    '}'
)
$cleanContent + $styles | Set-Content 'd:\Hirehack\style.css' -Encoding utf8
